### ISSUE TITLE
customizing docker daemon to listen on internal addresses

### ISSUE THREAD

**Issue by dvizzini** [cxmcc/ecsctl#1]
Thank you so much for writing this repo.

An interactive shell would be invaluable to me, but I cannot figure out what you mean by "customizing docker daemon to listen on internal addresses."

I see the comand `iptables --insert INPUT 1 --in-interface docker+ --protocol tcp --destination-port MYDOCKERPORT --jump DROP` [here](https://github.com/aws/amazon-ecs-cli/issues/143). should I run my docker command with a `-p MYDOCKERPORT` option? Should I run the `iptables` command on my laptop. Would this allow me to interactively exec into a container in ecs?

Thank you.

-Daniel Vizzini

**Comment by cxmcc** [comment]
@dvizzini The command is a security enhancement for the containers.

To allow you to execute commands into a container, the container instances need to listen on a port to allow communicating with the docker daemon API on the container instances from your computer.

**Comment by dvizzini** [comment]
Thanks.
